### ISSUE TITLE
why kaspersky endpoint security tell me trojan

### ISSUE THREAD

**Issue by avaisa** [louis030195/screen-pipe#83]
![image](https://github.com/user-attachments/assets/1cc96d42-c579-4071-ab0c-60f233080c48)

**Comment by louis030195** [comment]
Hey this is because we don't "sign" builds yet, which is why you will see warning from Windows or antivirus 

However all the code is open source, we have nothing to hide and no reason to do so, you don't need to worry about this.

We will take actions to make sure Windows does not send this kind of warning in the near future
